name: MacOS Qt6
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'BUILD.md'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'BUILD.md'
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        build_type: [Release, RelWithDebInfo]
        qt_ver: [6.0.0]
        qt_arch: [clang_64]
    env:
      targetName: lemon
    steps:
      - name: cacheQt
        id: MacosCacheQt
        uses: actions/cache@v1
        with:
          path: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
          key: ${{ runner.os }}-Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
#      - name: setupQt
#        if: steps.MacosCacheQt.outputs.cache-hit == 'true'
#        shell: bash
#        env:
#          QtPath: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
#        run: |
#          qt_Path=${env:QtPath}
#          echo "Qt5_DIR=\"$QtPath\"" >> $GITHUB_ENV
#          echo "${qt_Path}/bin" >> $GITHUB_PATH
      - name: Install Qt
        if: steps.MacosCacheQt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}

      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: macOS - ${{ matrix.qt_version }} - Build preparation - Install Packages
        run: |
          brew install ninja pkg-config
      - name: build macos
        env:
          Qt6_DIR: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
        run: |
          cmake . \
            -GNinja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DLEMON_QT6=ON \
            -DLEMON_BUILD_INFO="Build for macOS" \
            -DLEMON_BUILD_EXTRA_INFO="Build on $(uname -sr)" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13
          cmake --build . --parallel $(sysctl -n hw.logicalcpu)
      # tag 打包
      - name: package
        env:
          Qt6_DIR: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
        run: |
          # 拷贝依赖
          #mv ${targetName} ${targetName}.app
          export PATH=$Qt6_DIR/bin:$PATH
          macdeployqt ${targetName}.app -qmldir=. -verbose=1 -dmg
      - name: Upload artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ env.targetName }}-${{ matrix.build_type }}.dmg
          path: ${{ env.targetName }}.dmg
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ env.targetName }}.dmg
          asset_name: ${{ env.targetName }}-${{ matrix.build_type }}.dmg
          tag: ${{ github.ref }}
